// PoC seed data — replace with live Firestore data once pipeline has credits
export const SEED_VIDEOS = [
  {
    id: 'seed-1',
    title: 'Donald Hoffman: Reality, Consciousness & the Nature of Existence',
    channelName: 'Lex Fridman Podcast',
    thumbnailUrl: 'https://img.youtube.com/vi/iDbdXTMnOmE/hqdefault.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=iDbdXTMnOmE',
    scores: { overall: 4.6 },
    scoreRationale: 'Rigorous philosophical and scientific exploration of consciousness as the ground of reality. Hoffman\'s interface theory offers a genuinely novel framework.',
    tags: ['consciousness', 'quantum'],
    publishedAt: '2022-10-01T00:00:00Z',
  },
  {
    id: 'seed-2',
    title: 'Rupert Sheldrake: The Science Delusion — Morphic Resonance & Collective Memory',
    channelName: 'Rupert Sheldrake',
    thumbnailUrl: 'https://img.youtube.com/vi/JKHUaNAxsTg/hqdefault.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=JKHUaNAxsTg',
    scores: { overall: 4.4 },
    scoreRationale: 'Sheldrake challenges the materialist assumptions of mainstream science with decades of field research into morphic fields and collective memory.',
    tags: ['consciousness', 'energy', 'evolution'],
    publishedAt: '2023-03-15T00:00:00Z',
  },
  {
    id: 'seed-3',
    title: 'Joe Dispenza: Breaking the Habit of Being Yourself',
    channelName: 'Joe Dispenza',
    thumbnailUrl: 'https://img.youtube.com/vi/LkTe5-sMEBo/hqdefault.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=LkTe5-sMEBo',
    scores: { overall: 4.3 },
    scoreRationale: 'Practical neuroscience meets meditation — Dispenza bridges the gap between quantum field theory and personal transformation with clinical grounding.',
    tags: ['meditation', 'healing', 'manifestation'],
    publishedAt: '2023-06-20T00:00:00Z',
  },
  {
    id: 'seed-4',
    title: 'Ross Coulthart: UAP Disclosure — What the Government Actually Knows',
    channelName: 'NewsNation',
    thumbnailUrl: 'https://img.youtube.com/vi/vdp9p7vBkrA/hqdefault.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=vdp9p7vBkrA',
    scores: { overall: 4.7 },
    scoreRationale: 'One of the most credible investigative journalists in UAP reporting delivers new sourced information on the state of government disclosure efforts.',
    tags: ['UAP', 'disclosure'],
    publishedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'seed-5',
    title: 'Gregg Braden: The Science of Miracles — Heart Intelligence & the Field',
    channelName: 'Gregg Braden Official',
    thumbnailUrl: 'https://img.youtube.com/vi/4_rMPbeddOE/hqdefault.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=4_rMPbeddOE',
    scores: { overall: 4.2 },
    scoreRationale: 'Braden synthesizes ancient wisdom and modern science around the heart\'s electromagnetic field and its relationship to collective healing.',
    tags: ['energy', 'healing', 'consciousness'],
    publishedAt: '2023-09-05T00:00:00Z',
  },
  {
    id: 'seed-6',
    title: 'Dean Radin: Consciousness & the Quantum — Psi Research at the Institute of Noetic Sciences',
    channelName: 'Institute of Noetic Sciences',
    thumbnailUrl: 'https://img.youtube.com/vi/qpgNbKrTjhU/hqdefault.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=qpgNbKrTjhU',
    scores: { overall: 4.5 },
    scoreRationale: 'Decades of rigorous lab research on psi phenomena presented with scientific integrity. Radin makes a compelling evidence-based case for consciousness as fundamental.',
    tags: ['consciousness', 'quantum', 'synchronicity'],
    publishedAt: '2023-11-18T00:00:00Z',
  },
  {
    id: 'seed-7',
    title: 'Tom Campbell: My Big TOE — A Theory of Everything Based on Consciousness',
    channelName: 'Tom Campbell',
    thumbnailUrl: 'https://img.youtube.com/vi/rrpBQoRqEG8/hqdefault.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=rrpBQoRqEG8',
    scores: { overall: 4.4 },
    scoreRationale: 'Former NASA physicist builds a unified theory placing consciousness as the foundational substrate of reality, grounded in digital physics and decades of out-of-body research.',
    tags: ['consciousness', 'quantum', 'evolution'],
    publishedAt: '2023-07-12T00:00:00Z',
  },
  {
    id: 'seed-8',
    title: 'Bruce Lipton: The Biology of Belief — How Perception Shapes Reality',
    channelName: 'Bruce Lipton',
    thumbnailUrl: 'https://img.youtube.com/vi/82ShSNuru6c/hqdefault.jpg',
    youtubeUrl: 'https://www.youtube.com/watch?v=82ShSNuru6c',
    scores: { overall: 4.1 },
    scoreRationale: 'Lipton\'s epigenetics research fundamentally challenges genetic determinism, demonstrating that environment and belief directly influence cellular expression.',
    tags: ['healing', 'consciousness', 'energy'],
    publishedAt: '2023-08-22T00:00:00Z',
  },
]
